import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import App from "../components/App"
import { Router } from "react-router";
import buildHasuraProvider from 'ra-data-hasura';
import { Admin, Resource } from 'react-admin';
import { ApolloClient, InMemoryCache } from "@apollo/client";
import authProvider from '../utils/authProvider';
import { auth0 } from "../utils/authProvider";
import { createBrowserHistory as createHistory } from "history";
import { ProductList, ProductCreate } from './products';
import Dashboard from "../components/Dashboard";
import LoginPage from "./login";



const createApolloClient = async (token) => {
    return new ApolloClient({
        uri: 'https://react-admin.hasura.app/v1/graphql',
        cache: new InMemoryCache(),
        headers: {
            'Authorization': `Bearer ${token}` || null,
        }
    })
}

const history = createHistory();



export default function Home() {

  const [dataProvider, setDataProvider] = useState({});

    useEffect(() => {
        const buildDataProvider = async () => {

            const isAuthenticated = await auth0.isAuthenticated();
            if(!isAuthenticated) {
                return;
            }
            const token = await auth0.getIdTokenClaims();
            const idToken = token.__raw;
            console.log(idToken);

            const apolloClient = await createApolloClient(idToken);

            const dataProvider = await buildHasuraProvider({
                client: apolloClient
            });
            setDataProvider(() => dataProvider);
        }
        buildDataProvider();
    }, []);



  return (
    <div className={styles.container}>
      <Head>
        <title>Next Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 >
          Welcome to <a href="https://nextjs.org">Next.js Admin!</a>
        </h1>
        <Admin 
            dataProvider={dataProvider} 
            authProvider={authProvider}
            title="Hasura Dashboard"
            dashboard={Dashboard}
            history={History}
            loginPage={LoginPage}
        >
            <Resource name="products" list={ProductList} create={ProductCreate}></Resource>
        </Admin>
    </div>
  )
}


export async function getServerSideProps() {
  const options = {
    methods: 'POST',
    body: JSON.stringify({
      query: `query fetchProducts {
        product {
          id
          name

        }
      }`,
      operationName: "fetchProducts"
    })
  }

//   const request = await fetch(
//     `https://react-admin.hasura.app/v1/graphql{
//       requests[Dashboard]?.url || requests.fetchTrending.url
//     }`
//   ).then((res) => res.json());

//   return {
//     props: {
//       results: Dashboard
//     },
//   };
}